-- MySQL Script generated by MySQL Workbench
-- Sat Mar 24 10:39:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sidpla
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sidpla
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sidpla` DEFAULT CHARACTER SET utf8 ;
USE `sidpla` ;

-- -----------------------------------------------------
-- Table `sidpla`.`estado_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`estado_domicilio` (
  `Estado_dom` VARCHAR(50) NOT NULL COMMENT 'Describe el estado del domicilio (entregado, no entregado)',
  `estado_e_dom` TINYINT NOT NULL,
  PRIMARY KEY (`Estado_dom`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`pizzeria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`pizzeria` (
  `Nit_Pizzeria` BIGINT(20) NOT NULL COMMENT 'Número de identificación de  la pizzería. ',
  `Nom_Pizzeria` VARCHAR(45) NOT NULL COMMENT 'Nombre de la pìzzería. ',
  `Dir_Pizzeria` VARCHAR(50) NOT NULL COMMENT 'dirección de la pizzería. ',
  `Tel_Pizzeria` BIGINT(15) NOT NULL COMMENT 'Número Telefónico fijo de la pìzzería. ',
  `Cel_Pizzeria` BIGINT(15) NULL DEFAULT NULL COMMENT 'Número de celular de la pizzería. ',
  `Logo_Pizzeria` VARCHAR(70) NOT NULL COMMENT 'Logotipo de la pizzería. ',
  PRIMARY KEY (`Nit_Pizzeria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`domicilio` (
  `Cod_dom` INT NOT NULL AUTO_INCREMENT COMMENT 'Es el codigo por el cual de identifica el domicilio.',
  `Fecha_Hora` DATE NULL COMMENT 'Es la fecha en la que se realizo el domicilio.',
  `Direc_Dom` VARCHAR(60) NOT NULL COMMENT 'es la direccion del destino del domicilio a entregar',
  `Valor_Total` DECIMAL(10) NULL COMMENT 'Es la suma de los valores subtotales.',
  `Observacion_dom` VARCHAR(123) NULL COMMENT 'Observaciones acerca del domicilio. ',
  `estado_domicilio_Estado_dom` VARCHAR(50) NOT NULL,
  `pizzeria_Nit_Pizzeria` BIGINT(20) NOT NULL,
  PRIMARY KEY (`Cod_dom`),
  INDEX `fk_domicilio_estado_domicilio1_idx` (`estado_domicilio_Estado_dom` ASC),
  INDEX `fk_domicilio_pizzeria1_idx` (`pizzeria_Nit_Pizzeria` ASC),
  CONSTRAINT `fk_domicilio_estado_domicilio1`
    FOREIGN KEY (`estado_domicilio_Estado_dom`)
    REFERENCES `sidpla`.`estado_domicilio` (`Estado_dom`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_domicilio_pizzeria1`
    FOREIGN KEY (`pizzeria_Nit_Pizzeria`)
    REFERENCES `sidpla`.`pizzeria` (`Nit_Pizzeria`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`tipo_doc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`tipo_doc` (
  `tipo_doc` VARCHAR(45) NOT NULL COMMENT 'describe si el documento es CC, TI, CE, etc.',
  `estado_tipo_doc` TINYINT NOT NULL,
  PRIMARY KEY (`tipo_doc`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`rol` (
  `Rol` VARCHAR(45) NOT NULL COMMENT 'describe si el rol es cliente empleado o  gerente  ',
  `estado_rol` TINYINT NOT NULL,
  PRIMARY KEY (`Rol`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`persona` (
  `Num_Documento_per` VARCHAR(15) NOT NULL COMMENT 'es el numero de identificacion de la persona ',
  `Primer_Nombre_per` VARCHAR(45) NOT NULL COMMENT 'es el nombre 1 de la persona ',
  `Segundo_Nombre_per` VARCHAR(45) NULL DEFAULT NULL COMMENT 'es el nombre 2 de la persona ',
  `Primer_Apellido_per` VARCHAR(45) NOT NULL COMMENT 'es el apellido 1 de la persona',
  `Segundo_Apellido_per` VARCHAR(45) NULL COMMENT 'es el apellido 2 de la persona ',
  `Usuario_login` VARCHAR(45) NOT NULL COMMENT 'es el nombre de usuario con el que se identifica la persona para ingresar al sistema ',
  `Pass_login` VARCHAR(256) NOT NULL COMMENT 'es la contraseña con la que la persona ingresa al sistema ',
  `Tel_per` BIGINT(15) NULL DEFAULT NULL COMMENT 'es el telefono en el que se pueda localizar a la persona ',
  `Cel_per` BIGINT(15) NULL DEFAULT NULL COMMENT 'es el telefono celular en el que se puede localizar a la persona ',
  `Direc_per` VARCHAR(60) NOT NULL COMMENT 'es la direccion de vivienda de la persona ',
  `Correo_per` VARCHAR(45) NULL DEFAULT NULL COMMENT 'es el correo electronico que utiliza la persona ',
  `tipo_doc` VARCHAR(45) NOT NULL,
  `rol_Rol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Num_Documento_per`, `tipo_doc`),
  UNIQUE INDEX `Usuario_login_UNIQUE` (`Usuario_login` ASC),
  INDEX `fk_persona_tipo_doc1_idx` (`tipo_doc` ASC),
  INDEX `fk_persona_rol1_idx` (`rol_Rol` ASC),
  CONSTRAINT `fk_persona_tipo_doc1`
    FOREIGN KEY (`tipo_doc`)
    REFERENCES `sidpla`.`tipo_doc` (`tipo_doc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_rol1`
    FOREIGN KEY (`rol_Rol`)
    REFERENCES `sidpla`.`rol` (`Rol`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`opinion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`opinion` (
  `Cod_Opinion` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'es el codigo  que identifica la opinion dada por la  persona ',
  `Opinion` VARCHAR(250) NOT NULL COMMENT 'es la opinion dada por el cliente ',
  `persona_Num_Documento_per` VARCHAR(15) NOT NULL,
  `persona_tipo_doc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_Opinion`),
  INDEX `fk_opinion_persona1_idx` (`persona_Num_Documento_per` ASC, `persona_tipo_doc` ASC),
  CONSTRAINT `fk_opinion_persona1`
    FOREIGN KEY (`persona_Num_Documento_per` , `persona_tipo_doc`)
    REFERENCES `sidpla`.`persona` (`Num_Documento_per` , `tipo_doc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`tipo_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`tipo_producto` (
  `tipo_prod` VARCHAR(50) NOT NULL COMMENT 'Describe el tipo de producto (pizza, postre, bebida, etc).',
  `estado_tipo_prod` TINYINT NOT NULL,
  PRIMARY KEY (`tipo_prod`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`tamaño`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`tamaño` (
  `tamaño` VARCHAR(50) NOT NULL COMMENT 'Describe el tamaño del producto. ',
  `estado_tamaño` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tamaño`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`producto` (
  `Cod_producto` INT NOT NULL AUTO_INCREMENT COMMENT 'Es el codigo por el cual se identifica el producto.',
  `Nom_prod` VARCHAR(45) NOT NULL COMMENT 'Nombre por el que se identifica el producto.',
  `Desc_prod` VARCHAR(100) NOT NULL COMMENT 'Descripción del producto.',
  `Foto_prod` VARCHAR(70) NOT NULL COMMENT 'Imagen, foto por la que se identifica el producto.',
  `Stok_min` INT(11) NULL DEFAULT NULL COMMENT 'Cantidad minima que puede existir del producto',
  `Stok_max` INT(11) NULL DEFAULT NULL COMMENT 'Cantidad maxima  que puede existir del producto',
  `Cantidad_exist` INT(11) NULL DEFAULT NULL COMMENT 'Numero total de unidades existentes del producto',
  `tipo_producto_tipo_prod` VARCHAR(50) NOT NULL,
  `tamaño_tamaño` VARCHAR(50) NOT NULL,
  `Valor_unitario` DECIMAL(10) NULL,
  PRIMARY KEY (`Cod_producto`),
  INDEX `fk_producto_tipo_producto1_idx` (`tipo_producto_tipo_prod` ASC),
  INDEX `fk_producto_tamaño1_idx` (`tamaño_tamaño` ASC),
  CONSTRAINT `fk_producto_tipo_producto1`
    FOREIGN KEY (`tipo_producto_tipo_prod`)
    REFERENCES `sidpla`.`tipo_producto` (`tipo_prod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_producto_tamaño1`
    FOREIGN KEY (`tamaño_tamaño`)
    REFERENCES `sidpla`.`tamaño` (`tamaño`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`domicilio_has_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`domicilio_has_producto` (
  `domicilio_Cod_dom` INT NOT NULL,
  `producto_Cod_producto` INT NOT NULL,
  `Cantidad` INT ZEROFILL NOT NULL,
  `Valor_subtotal` DECIMAL(10) NULL,
  PRIMARY KEY (`domicilio_Cod_dom`, `producto_Cod_producto`),
  INDEX `fk_domicilio_has_producto_producto1_idx` (`producto_Cod_producto` ASC),
  INDEX `fk_domicilio_has_producto_domicilio1_idx` (`domicilio_Cod_dom` ASC),
  CONSTRAINT `fk_domicilio_has_producto_domicilio1`
    FOREIGN KEY (`domicilio_Cod_dom`)
    REFERENCES `sidpla`.`domicilio` (`Cod_dom`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_domicilio_has_producto_producto1`
    FOREIGN KEY (`producto_Cod_producto`)
    REFERENCES `sidpla`.`producto` (`Cod_producto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sidpla`.`persona_has_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sidpla`.`persona_has_domicilio` (
  `persona_Num_Documento_per` VARCHAR(15) NOT NULL,
  `persona_tipo_doc` VARCHAR(45) NOT NULL,
  `domicilio_Cod_dom` INT NOT NULL,
  PRIMARY KEY (`persona_Num_Documento_per`, `persona_tipo_doc`, `domicilio_Cod_dom`),
  INDEX `fk_persona_has_domicilio_domicilio1_idx` (`domicilio_Cod_dom` ASC),
  INDEX `fk_persona_has_domicilio_persona1_idx` (`persona_Num_Documento_per` ASC, `persona_tipo_doc` ASC),
  CONSTRAINT `fk_persona_has_domicilio_persona1`
    FOREIGN KEY (`persona_Num_Documento_per` , `persona_tipo_doc`)
    REFERENCES `sidpla`.`persona` (`Num_Documento_per` , `tipo_doc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_persona_has_domicilio_domicilio1`
    FOREIGN KEY (`domicilio_Cod_dom`)
    REFERENCES `sidpla`.`domicilio` (`Cod_dom`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
